content:
  - name: blog
    label: Blog
    path: src/content/blog
    filename: '{fields.title}.md'
    type: collection
    view:
      fields: [heroImage, title, pubDate]
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: text
      - name: author
        label: Author
        type: string
      - name: pubDate
        label: Publication Date
        type: date
        options:
          format: yyyy/MM/dd
      - name: heroImage
        label: Hero Image
        type: image
      - name: avatarImage
        label: Avatar Image
        type: image
      - name: theme
        label: Theme
        type: string
      - name: body
        label: Body
        type: rich-text

  - name: site-settings
    label: Site Settings
    path: src/config/site.json
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
        description: Will be used for any page with no description.
      - name: url
        label: Website URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: cover
        label: Preview image
        type: image
        description: Image used in the social preview on social networks (e.g. Facebook, Twitter...)

media:
  input: src/assets
  output: ../../assets
